a=input('Enter the first number: ')
b=input('Enter the second number: ')
a=int(a)
b=int(b)
ab1=(a+b)
print('Addition: ',ab1)
ab2=(a-b)
print('Subtraction: ',ab2)
ab3=(a*b)
print('Multiplication: ',ab3)
ab4=(a/b)
print('Dividion: ',ab4)